version: '3.8'

services:
  microservices:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/microservices.conf:/etc/nginx/conf.d/microservices.conf
      - ./nginx/conf.d/base.txt:/etc/nginx/conf.d/base
      - ./projetos:/var/www/html



# networks:
#   host: 
#     driver: host
