version: '3.8'

services:
  microservices:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/microservices.conf:/etc/nginx/conf.d/microservices.conf
      - ./nginx/conf.d/base.txt:/etc/nginx/conf.d/base
      - ./projetos:/home/projects/
      - ./nginx/logs/access.log:/var/log/nginx/b4b/access.log
      - ./nginx/logs/error.log:/var/log/nginx/b4b/error.log



# networks:
#   host: 
#     driver: host
